<a href="https://colab.research.google.com/github/kimmokyun/python2/blob/master/python_12_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 6. 3차원 이상에서 차원 구분법

In [5]:
import numpy as np

In [6]:
# 0부터 24미만 까지 생성
b = np.arange(24).reshape(2,3,4)
b
print(b) # print하면 array라는 글자는 안보인다.
# 공백은 그대로 보인다. -> 차원 구분 가능

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
b[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
b[0,1]

array([4, 5, 6, 7])

In [10]:
b[1,1]

array([16, 17, 18, 19])

In [11]:
b[0,1,3]

7

### 7 fancy indexing와 indexing 차이
 - indexing은 원래 차원에서 하나 감소해서 가져오고 fancy indexing은 원래 차원 그대로 가져온다.
 

In [12]:
# indexing은 차원이 하나 감소해서 가져온다. (3차원 2차원으로 가져온다.)
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
# fancy indexing은 원래 3차원 그대로 가져온다.
b[[0]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [14]:
b[[0],:,:] # b[0]은 b[0,:,:]의 단축 표현이다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [15]:
# b의 0번째 공간, 1번째 행 미만, 열 전체
b[0, :1, :]

array([[0, 1, 2, 3]])

# 8 Elipsis
...(Ellipsis)은 이후로 모든 것을 의미한다.

In [16]:
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
b[0] #생략기법
b[0,:,:] # slicing기법
b[0,...] # Ellipsis 기법


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
# 숫자 1, 5, 9 만 가져오라하면
b[0,:,1]

array([1, 5, 9])

In [20]:
b[0,[0,1,2],:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#숫자 1,5,9,3,7,11
b[0,:,[1,3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [22]:
# 숫자 4,5,6,7,16,17.18,19 가져오기
b[:,:,3]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [23]:
b[:,:,3:4]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [25]:
b[:,:,[3]]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [27]:
c = b[:,:,3]
c.shape

(2, 3)

In [28]:
np.arange(1000000)

array([     0,      1,      2, ..., 999997, 999998, 999999])

# 줄임표현(...)
출력해야할 데이터 수가 엄청 클 때 보이는 ...은 Elipsis와 다르다.

In [29]:
# out에 나오는 ...은 단순히 줄임표현이다.
np.arange(100000000)

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

In [30]:
np.set_printoptions(edgeitems=6)


In [31]:
np.arange(10000)

array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
       9998, 9999])

# 연산
numpy연산의 기본은 두개의 shape이 같아야 한다.

In [32]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a.shape

(3, 4)

In [34]:
b = np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
b.shape

(3, 4)

In [ ]:
# numpy는 elementwise로 vectorize연산을 한다.
# vectorize는 데이터의 연산을 일고라적으로 처리하는 기능이다.

In [36]:
# 같은 위치의 원소끼리 더해 준다.
a+b

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [37]:
# python의 list에서 + 연산자는 elementwise가 아니라 list를 확장시킨다. (연결)
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [38]:
@np.vectorize
def plus(a,b):
  return a+b
plus([1,2,3],[4,5,6]) #elementwise, vectrorize

array([5, 7, 9])

In [39]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
b = np.arange(6,12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
a*b # elementwise 끼리

array([[ 0,  7, 16],
       [27, 40, 55]])

In [42]:
type(np.array(3))

numpy.ndarray

In [43]:
c = np.matrix([[1,2],[3,4]])

In [44]:
type(c)

numpy.matrix

numpy에서는 ndarry이외에 matrix라는 자료형도 존재한다.
matrix에서는 * 연산자는 행렬곱을 의미한다.


In [45]:
# matrix * matrix = 행렬곱
# 1*1+2*3     1*2+2*4
# 3*1+4*3    3*2 + 4*4
c*c

matrix([[ 7, 10],
        [15, 22]])

ndarry에서 행렬곱 연산자 @이다.
python재단에서 numpy를 위해 만들어준 연산자이다.

In [46]:
a.shape

(2, 3)

In [47]:
b.shape

(2, 3)

In [48]:
a @ b

ValueError: ignored

행렬곱을 하기 위해서는 shape가 맞아야 한다.
T는 transpose(전치)의 약자이다.

In [49]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
# 전치 행렬 :  행과 열을 바꾼다
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [51]:
a @ a.T

array([[ 5, 14],
       [14, 50]])

# matrix는 @와 * 모두가 가능하다.

In [52]:
c * c.T

matrix([[ 5, 11],
        [11, 25]])

In [53]:
c @ c.T

matrix([[ 5, 11],
        [11, 25]])

함수방법으로 np.dot()을 사용할 수 있다.


In [54]:
np.dot(a, a.T)

array([[ 5, 14],
       [14, 50]])

In [55]:
np.dot(c,c.T)

matrix([[ 5, 11],
        [11, 25]])

method방법으로도 행렬곱 할 수 있다.
function방법과 사용하는 방법이 다르므로 주의한다.

In [56]:
np.dot(a,a.T) # function 함수방식

array([[ 5, 14],
       [14, 50]])

In [57]:
a.dot(a.T) # method 방식

array([[ 5, 14],
       [14, 50]])

# 10 broadcasting
 python은 배열과 숫자간에 연산을 할 수 있다.
 

[1,2,3] + 1 (x)      
[1,2,3] + [1,2,3] 연결 (o)    
[1,2,3] * 1  반복(o)    
[1,2,3] * [1,2,3] (x)    

In [58]:
a + 1

array([[1, 2, 3],
       [4, 5, 6]])

broadcasting이란 모양(shape)이 안맞는데, 특정한 조건에 맞으면 모양을 같게 만들어 연산하는 기능이다.  
위 연산에서 1을 a와 같은 모양으로 만들어 준다.  
[[1,1,1],   
[1,1,1]]
    
(1) broadcastiong가 안되는 경우와 가능한 경우


In [59]:
array([[0,1,2],[3,4,5]])

NameError: ignored

In [60]:
a+np.array([3,4,5])

array([[ 3,  5,  7],
       [ 6,  8, 10]])

# 11 strides
strides는 다음 원소끼리 메모리 크기를 차원별로 알려준다.
c의 포인터 개념을 알고 있으면 이해하기가 쉽다.


In [64]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
a.strides

(32, 8)

In [66]:
a.dtype

dtype('int64')

In [67]:
a.itemsize

8

In [68]:
#열의 원소개수 * itemsize = 행의 메모리 간격
# itemsize = 열의 메모리 간격
a.shape

(3, 4)

# 12 axis
axis 는 다차원 배열을 연산할때 기준이 되는 축이다.

In [69]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
np.sum(a)

66

In [71]:
np.sum(a, axis=0) # a배열은 2차원이므로 axis = 0은 행기준(행마다 더해라)

array([12, 15, 18, 21])

In [ ]:
np.sum(a, axis=1) # a배열은 2차원이므로 axis = 1은 열기준이다(열마다)

# axis는 3차원 이상에도 사용할수 있다.

In [91]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(0,0,1)(0,0,1)(0,0,2)(0,0,3)  
(0,1,1)(0,1,1)(0,1,2)(0,1,3)  
(0,2,1)(0,2,1)(0,2,2)(0,2,3)  
  
  
(1,0,1)(1,0,1)(1,0,2)(1,0,3)  
(1,1,1)(1,1,1)(1,1,2)(1,1,3)  
(1,2,1)(1,2,1)(1,2,2)(1,2,3)  


In [92]:
np.sum(a, axis=0) # 공간기준 (공간마다)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [93]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [94]:
a = np.split(a,2, axis=0)
a

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [95]:
#a는 바뀌지 않으므로 재할당을 한다.

In [96]:
print(type(a))
print(type(a[0]))

<class 'list'>
<class 'numpy.ndarray'>


In [97]:
b = np.arange(24)
b = np.split(b,2)
b

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

### indices_or_sections
split 시리즈 함수들의 두번째 파라미터 이름이 indices_or_sections이다  

숫자를 묶어서 넣으면 구간으로 쪼개진다.

In [98]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [99]:
#section
#처음부터 ~ 2미만 : [0,1]
#2부터 ~ 3미만 : [2]
#3부터 끝까지 : [3,4,5...]
np.hsplit(a,(2,3))

[array([0, 1]),
 array([2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23])]

# 13 array 합치기

In [101]:
a = np.arange(24)
x, y, z = np.split(a,3)
print(x)
print(y)
print(z)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]


# hstack은 horizental(가로)로 합쳐준다.


In [102]:
np.vstack((x,y))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
# 원래 shape 크기 그대로 유지를 한다.

In [103]:
np.concatenate((x,y)) # axis =0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# np.newaxis 대신에 None을 써도 된다.
None은 직관적이지 않고 헷갈려서 np.newaxis를 만들었다.  
numpy를 만들때 python의 모든 연산자를 다 사용해서 남는 연산자가 없엇다.    
     그래서 None를 이용했다

In [105]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
np.expand_dims(a,0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

# 한줄로 펴기


In [ ]:
# flatten

In [108]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
# flatten()은 결과를 return하고 메모리의 값은 변경되지 않는다.
b=a.flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [110]:
a.shape

(3, 4)